apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isprediksjon
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 2Gi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvisprediksjon
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://isprediksjon.nais.preprod.local"
  webproxy: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SM2013_MANUELL_BEHANDLING
      value: privat-syfo-sm2013-manuellBehandling
    - name: KAFKA_SM2013_AUTOMATISK_BEHANDLING_TOPIC
      value: privat-syfo-sm2013-automatiskBehandling
    - name: KAFKA_SMREGISTER_RECIEVED_SYKMELDING_BACKUP_TOPIC
      value: privat-syfosmregister-received-sykmelding-backup
    - name: KAFKA_SM2013_BEHANDLINGSUTFALL_TOPIC
      value: privat-syfo-sm2013-behandlingsUtfall
    - name: KAFKA_SMREGISTER_BEHANDLINGSUTFALL_BACKUP_TOPIC
      value: privat-syfosmregister-behandlingsutfall-backup
    - name: KAFKA_SYFO_SYKMELDINGSTATUS_LEESAH_TOPIC
      value: aapen-syfo-sykmeldingstatus-leesah-v1
    - name: KAFKA_SYFO_REGISTER_STATUS_BACKUP_TOPIC
      value: privat-syfo-register-status-backup
    - name: DATABASE_MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: DATABASE_NAME
      value: isprediksjon
    - name: ISPREDIKSJON_DB_URL
      value: jdbc:postgresql://b27dbvl015.preprod.local:5432/isprediksjon
    - name: AKTORREGISTER_V1_URL
      value: "https://app-q1.adeo.no/aktoerregister/api/v1"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.preprod.local"
    - name: SYFOSYKETILFELLE_URL
      value: "https://syfosyketilfelle.nais.preprod.local"
    - name: IS_PROCESS_OPPFOLGINGSTILFELLE_ON
      value: "true"
    - name: AADDISCOVERY_URL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration"
    - name: LOGINSERVICE_CLIENT_ID
      value: 38e07d31-659d-4595-939a-f18dce3446c5
    - name: TILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.nais.preprod.local"

